name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix Kotlin version
        run: |
          if [ -f android/build.gradle ]; then
            sed -i "s/ext.kotlin_version = '.*'/ext.kotlin_version = '1.9.22'/" android/build.gradle
          fi
          if [ -f android/settings.gradle ]; then
            sed -i "s/kotlin_version = '.*'/kotlin_version = '1.9.22'/" android/settings.gradle
          fi
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.9'
      - run: flutter pub get
      - run: flutter build apk --release --android-skip-build-dependency-validation
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
